### ISSUE TITLE
The combined receiver function does not return anything

### ISSUE THREAD

**Issue by built-tools** [ladybug-tools/honeybee-radiance-folder#119]
I want to start using this function to trace rays simultaneously for all the apertures within a grid (as the function intends to do I presume). Right now this function does not return the name of the receivers that are written out. While there is obviously a way to work around that, it would be far more straightforward if this function was returning the paths of the combined receivers it was writing out. (I guess it would also be in line with programming best practices).
https://github.com/ladybug-tools/honeybee-radiance-folder/blob/master/honeybee_radiance_folder/folder.py#L507-L543

Any reason this wasn't done in the first place @mikkelkp  or @mostaphaRoudsari ?

**Comment by built-tools** [comment]
https://github.com/ladybug-tools/honeybee-radiance-folder/blob/master/honeybee_radiance_folder/folder.py#L507-L543

**Comment by mikkelkp** [comment]
> Any reason this wasn't done in the first place @mikkelkp or @mostaphaRoudsari ?

At the time of implementation I didn't use the function as a minor step in a larger script. I guess that's why I didn't add the paths to be returned. I think your suggestion is reasonable.

**Comment by built-tools** [comment]
@mikkelkp Understood. I am trying to check if there is a way to avoid directing output files with the `#!rfluxmtx..o=` comment option. So for the time being I am not using this function directly. I thought of pointing this out because this might be one of the approaches that we fall back on eventually.
