### ISSUE TITLE
Check if two phase simulation is possible in 'scene mapping'

### ISSUE THREAD

**Issue by mikkelkp** [ladybug-tools/honeybee-radiance-folder#126]
We should check if the model have any static apertures and non-BSDF aperture groups. See [this](https://github.com/ladybug-tools/honeybee-radiance-folder/pull/125#discussion_r801702750).

**Comment by mostaphaRoudsari** [comment]
I think in that case we should generate an empty list so we can keep the workflow the same but it won't run any 2-phase calculations.
